### ISSUE TITLE
File plugins/bootstrap/bootstrap-5.3.0-alpha1-dist/css/bootstrap.min.css not found

### ISSUE THREAD

**Issue by Alex300** [seditio/cot_bootstrap#2]
Exception выскакивает сразу после установки.
надо в plugins/bootstrap/bootstrap.setup.php вместо bootstrap-5.3.0-alpha1-dist:

front=01:string::bootstrap-5.3.0-dist:
back=02:string::bootstrap-5.3.0-dist:

**Comment by seditio** [comment]
My bad: удалил 5.3.0-alpha1, но не исправил дефолтное конфиги
